<span class="container-fluid">
    <span class="row-fluid">
	<span class="span8 offset2" id="my_content_span">
<head>
  <link rel="stylesheet" href="iphone.css" type="text/css" />
  <meta name="viewport" content="user-scalable=no, width=device-width" />
  <title>Legal</title>
</head>
<body>
  <div id="header">
                <p><strong>Privacy Policy Statement</strong></p>
<p><strong>Effective on September 18, 2011.</strong></p>
<p>This Privacy Statement (&#8220;<strong>Statement</strong>&#8220;) describes the personal information we collect through our websites and mobile applications (the &#8220;<strong>Site</strong>&#8220;), and how we collect and use it. The terms &#8220;<strong>we</strong>&#8220;, &#8220;<strong>us</strong>&#8220;, and &#8220;<strong>DishClips</strong>&#8221; refer to DishClips a division of Nogalis, Inc, a California Corporation..</p>
<p><strong>      I.        </strong><strong>INFORMATION WE COLLECT AND HOW WE USE IT</strong></p>
<p><em>Account information.</em> We ask for and store information about you when you create an account on the Site, such as your name, email address, and signup location. You can also import your account information from a third party to make the DishClips registration process easier. We use your name to create your account name (first name and last initial), and we use your signup location to help target the Site to the town you live in. We use your email address to send you updates, provide services to you in connection with the Site, and to contact you on behalf of other users sending you messages, complements, and the like. We may also use your signup location, birth date, and gender (if you supply them) to display relevant advertising to you. You can change your account information at any time.</p>
<p><em>Location data.</em> The Site can provide helpful information based on where you are. If you tell us where you are (e.g., by allowing your mobile device to send us your location), we may store and use that information to provide you with location-based information and advertising. If you want to deactivate this feature, you can either reinstall the application or deactivate GPS on your mobile device. The Site also allows you to tell other users where you are, if you choose.</p>
<p><em>Third party services.</em> We allow you to access third party services, such as Facebook and Twitter, to share your selected Public Content with those services, and import information about who you are connected with on those other services so you can connect with them on the Site. You can always opt out on your DishClips account page. Some of those third party services may also provide us with information from your accounts there to enhance and personalize your use of this Site. For example, you can allow Facebook to tell us who your Facebook friends are so you can follow their activity on DishClips. You can adjust your DishClips privacy settings to block this feature, in which case we will delete the information that we receive from your accounts with those other services.</p>
<p><em>Activity and log data.</em> We automatically store information related to your use of the Site, such as the pages you view on the Site, your browser type, IP address, the phone numbers and names of businesses that you call through the Site, requested URL, browser language, referring URL, and the date and time of your visit. We use this type of information to administer the Site and provide the highest possible level of service to you. We also use this information in the aggregate to perform statistical analyses of user behavior and characteristics in order to measure interest in and use of the various areas of the Site.</p>
<p><em>Cookies.</em> We send cookies to your computer in order to uniquely identify your browser and improve the quality of our service. &#8220;<strong>Cookies</strong>&#8221; refer to small pieces of information that a website sends to your computer&#8217;s hard drive while you are viewing the Site. We may use both session cookies (which expire once you close your browser) and persistent cookies (which stay on your computer until you delete them). Persistent cookies can be removed by following your browser help file directions. If you choose to disable cookies, some areas of the Site may not work properly or at all. Our cookies are linked to your information, such as your name, email address and password. We enable some of our business partners to use cookies in conjunction with your use of the Site. We have no access to or control over the use of these cookies. These cookies collect information about your use of the Site, such as where you came from, which pages you visited within the Site, and possibly other sites you visit if those sites cooperate with the same third party, but do not collect your name, email address, contact information or other personally identifiable information that by itself would allow the third party to identify or contact you.</p>
<p><em>Feedback.</em> You should feel free to give us feedback, register a complaint, or ask questions about the Site. We may store your communications, including any personal information you include in them, so that we can effectively respond to you.</p>
<p><em>Administration.</em> We may use the information described above for routine administrative purposes, such as investigating abuses on the Site, responding to user inquiries and enforcing and applying our Terms of Service and Statement.</p>
<p><em>Data storage.</em> We store data in the United States.</p>
<p><strong>     II.        </strong><strong>TRANSFER OF INFORMATION</strong></p>
<p><em>Public Content.</em> If you post content for public view on the Site, we may distribute such Public Content to a wider audience by sharing it (or portions of it) with third parties so that they can publish it on their own websites and media platforms. We may ask them to credit you as the source of these contributions by including your account name and profile photo.</p>
<p><em>Third party service providers.</em> We may use third parties to provide technical and customer support, perform tracking and reporting functions, conduct quality assurance testing, perform payment processing and provide other services in connection with the Site. We may share information about you with them so that they can perform the services they are required to perform, but they are not permitted to use your personal information other than to provide the services requested by you.</p>
<p><em>Third party advertising.</em> Third parties serve some of the ads on the Site. We do not send any individualized personal information to them, but they may have access to information that they obtain through cookies or that you share with them yourself. You can opt-out of some these practices by visiting the Network Advertising Initiative&#8217;s opt-out page. Note that we do not rent, share, sell or trade personally identifiable information with third parties for their direct marketing purposes.</p>
<p><em>Aggregate information.</em> We may share non-personal information in the aggregate to third parties relating to user behavior in connection with actual or prospective business relationship with those third parties, such as advertisers and content distributors. For example, we may disclose the number of users that have been exposed to, or clicked on, advertising banners.</p>
<p><em>Business transfers.</em> We may share your information with our parent company, subsidiaries, joint ventures, or other companies under a common control that we may have now or in the future, in which case we will require them to honor this Statement. If another company acquires our company or all or substantially all of our assets, that company will possess your information, and will assume the rights and obligations with respect to that information as described in this Statement.</p>
<p><em>Investigations.</em> We reserve the right to investigate abuses on the Site, and enforce and apply our Terms of Service and Statement. We may disclose information about you to third parties if we have a good faith belief that such disclosure is reasonably necessary to (a) take action regarding suspected illegal activities; (b) enforce or apply our Terms of Service and Statement; (c) comply with legal process and law enforcement instructions and orders, such as a search warrant, subpoena, statute, judicial proceeding, or other legal process served on us; or (d) protect our rights, reputation, and property, or that of our users, affiliates, or the public.</p>
<p><strong>    III.        </strong><strong>MANAGING YOUR INFORMATION</strong></p>
<p>We provide a number of tools to manage the use of your information on the Site. You may receive weekly newsletter communications from us. However, despite any requests to close your account or your indicated email preferences, we may still need to contact you as required by law or on legal matters, for example to inform you of any updates to our Terms of Service or this Statement.</p>
<p><strong>    IV.        </strong><strong>LINKS</strong></p>
<p>The Site may contain links to third party websites with which we have no affiliation. Except as set forth herein, we do not share your personal information with those third parties, and are not responsible for their privacy practices. We suggest you read the privacy policies on all such third party websites.</p>
<p><strong>     V.        </strong><strong>OUR POLICY TOWARDS CHILDREN</strong></p>
<p>The Site is intended for general audiences and is not directed to children under 13. We do not knowingly collect personal information from children under 13. If you become aware that your child has provided us with personal information without your consent, please contact us using our contact link. If we become aware that a child under 13 has provided us with personal information without parental consent, we take steps to remove such information and terminate the child&#8217;s account.</p>
<p><strong>    VI.        </strong><strong>SECURITY</strong></p>
<p>We follow generally accepted industry standards to protect the personal information submitted to us, both during transmission and once we receive it. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security.</p>
<p><strong>   VII.        </strong><strong>DISPUTE RESOLUTION</strong></p>
<p>If you believe that DishClips has not adhered to this Statement you may write to the DishClips Privacy Office at the following address:</p>
<p>Nogalis, Inc.<br />
Attn: DishClips Privacy Officer<br />
4540 Campus Drive<br />
Newport Beach, CA 92660<br />
United States of America</p>
<p><strong>  VIII.        </strong><strong>MODIFICATIONS TO THIS STATEMENT</strong></p>
<p>We may revise this Statement from time to time. The most current version of the Statement will govern our use of your information and will always be located here. If we make a change to this Statement that, in our sole discretion, is material, we will notify you either by prominently posting a notice of such changes prior to implementing the change on the Site and/or via the email associated with your account. By continuing to access or use the Services after those changes become effective, you agree to be bound by the revised Statement</p>


  </div>


</body>
</span>
</span>
</span>